export const STATUS_CODE = {
  OK: 200,
  TRIPLEA: 151,
  CREATED: 201,
  ACCEPTED: 202,
  NO_CONTENT: 204,
  INFO: 250,
  NON_AUTHORITATIVE: 203,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  ALREADY_EXISTS: 409,
  PROXY_AUTH_FAILED: 412,
  UNSUPPORTED_MEDIA_TYPE: 415,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,
  VALIDATION_FAILURE: 450,
  INTERNAL_SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
  SERVER_TIMEOUT: 504,
};

export const ERROR_MSGS = {
  EITHER_EMAIL_OF_MOBILE:"Either send email or mobile number",
  SERVER_ERROR: "Unable to process, please try again",
  UNAUTHORIZED: "You are not authorized",
  CREATE_ERROR: "Failed to create resource",
  EMAIL_EXISTS: "Email already exists",
  MOBILE_EXISTS: "Mobile number already exists",
  NOT_FOUND: "Resource not found",
  USER_NOT_FOUND: "User not found",
  ACCOUNT_LOCKED: "Your account is locked, please reset your password",
  INVALID_LOGIN: "Invalid email or password",
  TOKEN_EXPIRED: "Token has expired",
  INTERNAL_SERVER_ERROR: "Internal server error",
  TOKEN_MISSING: "No token provided",
  INVALID_TOKEN: "Invalid token format",
  INVALID_OTP: "Invalid OTP",
  INVALID_CREDENTIALS: "Invalid credentials",
  PASSWORD_NOT_SET: "Password not set",
  INVALID_PASSWORD: "Invalid password",
  VALIDATION_FAILED: "Validation failed.",
  VALIDATION_ERROR: "Validation error.",
  ONLY_MULTIPART_OR_FORM_DATA: "Only multipart/form-data is allowed.",
};

export const INFO_MSGS = {
  SUCCESS: "Request successful",
  CREATED: "Resource created successfully",
  UPDATED: "Resource updated successfully",
  DELETED: "Resource deleted successfully",
  FOUND: "Data found.",
  USER_CREATED: "User created successfully",
  UPDATED_SUCCESSFULLY: "User updated successfully",
  DELETE_SUCCESSFULLY: "User deleted successfully",
  LOGIN_SUCCESS: "Logged in successfully",
  PASSWORD_CHANGED: "Password changed successfully",
  OTP_VERIFIED: "OTP verified successfully",
  EMAIL_SENT: "Verification email sent successfully",
  LOGOUT_SUCCESS: "Logged out successfully",

  OTP_GENERATED: "OTP generated successfully",
  PASSWORD_SET: "Password set successfully",
  PASSWORD_RESET_LINK_SENT: "Password reset link sent successfully",

  MSSG_SUCCESS: "Message sent successfully",
  MSSG_FOUND: "Messages found successfully",
};
